### PR TITLE
Multiple tasks

### PR DESCRIPTION
**Pull request by joelmoss**
Added the ability to pass more than one task name to the before or after blocks. see the #test_after_multiple test case.

### CODE REVIEW

**Comment by guillermo** [comment]
Nice !

Lots of thanks for the patch !

If you could remove turn dependency (that i think is a decision of the user to use it or not), i can merge it automatically.

**Comment by joelmoss** [comment]
Done!

**Comment by guillermo** [comment]
Il try to merge this today and realese the next version.

If you have time, to have a clean tree, can you run?:

git rebase -i f06628e^
git push -f

So the pull request is compacted in just one commit?

And of course, and yourself to the authors in the readme and the gemspec :-P

Thanks

**Comment by guillermo** [comment]
Merged!

**Comment by joelmoss** [comment]
Cheers!  

## 

Joel Moss

# Develop with Style at http://DevelopWithStyle.com

Call me +44 7791 503309
http://twitter.com/joelmoss
AIM: joelkmoss
MSIM: joel@joelmoss.info
Skype: joelmoss.info

**Pull request closed without merging**
